name: MedTrack CI

on:
  push:
    branches:
      - AWS_LAB
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    tags:
      - 'v*'

  # workflow_dispatch:

jobs:

  frontend-build:

    name: Frontend Build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build
        working-directory: frontend