name: MedTrack CI

on:
  push:
    branches:
      - AWS_LAB
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    tags:
      - 'v*'

  # workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Hello GitHub Actions
        run: echo "MedTrack GitHub Actions Started"