name: MedTrack CI

on:
  push:
    branches:
      - AWS_LAB

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Hello GitHub Actions
        run: echo "MedTrack GitHub Actions Started"
        
workflow_dispatch: